name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY_PATH: config/jwt/private.pem
      JWT_PUBLIC_KEY_PATH: config/jwt/public.pem
      ENV: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Install dependencies
      run: go mod tidy
 
    - name: Generate JWT keys
      run: |
        mkdir -p config/jwt
        openssl genpkey -algorithm RSA -out config/jwt/private.pem -pkeyopt rsa_keygen_bits:4096
        openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem

    - name: Run tests
      run: go test ./... -v

